Abstract the code & metadata of an MFA as a kfun().
cuter-testing/cuter pull request #179
Opened 2021-09-13 15:19 UTC by aggelgian

The intention is to make consumers of code unaware of how it is stored
in CutEr.

Each MFA will be an opaque kfun() and each module will be an opaque
kmodule(), and we will provide an API to access and modify them.

2021-09-13 18:09 UTC, Dspil approved these changes

2021-09-15 07:48 UTC, kostis requested changes
Looks OK, but I am a bit puzzled why you have declared `kfun()` as 
```erlang
-type kfun() :: ...
```
instead of
```erlang
-opaque kfun() :: ...
```
as mentioned as the intention of this PR in its commit message.

2021-09-15 09:11 UTC, aggelgian commented
> Looks OK, but I am a bit puzzled why you have declared `kfun()` as
> 
> ```erlang
> -type kfun() :: ...
> ```
> 
> instead of
> 
> ```erlang
> -opaque kfun() :: ...
> ```
> 
> as mentioned as the intention of this PR in its commit message.

Done.

2021-09-15 09:26 UTC, kostis approved these changes

2021-09-15 09:27 UTC, merged